$site = "https://site address here"

$sensitiveTargets = @(
    # env and config files
    "/.env",
    "/.env.local",
    "/.env.development", 
    "/.env.production",
    "/.env.staging",
    "/.env.test",
    "/.env.backup",
    "/.env.example",
    "/.env.sample",
    "/config.ini",
    "/config.php",
    "/config.json",
    "/config.yaml",
    "/config.yml",
    "/configuration.php",
    "/settings.ini",
    "/settings.php",
    "/settings.json",
    "/app.config",
    "/web.config",
    "/application.properties",
    "/config/config.ini",
    "/config/database.yml",
    "/config/secrets.yml",
    "/config/app.php",
    "/config/database.php",
    
    # common txt stuff
    "/config.txt",
    "/config/config.txt"
    "/config/settings.txt",
    "/configuration.txt",
    "/settings.txt",
    "/database.txt",
    "/db.txt",
    "/env.txt",
    "/environment.txt",
    "/secrets.txt",
    "/secret.txt",
    "/keys.txt",
    "/key.txt",
    "/passwords.txt",
    "/password.txt",
    "/pass.txt",
    "/credentials.txt",
    "/creds.txt",
    "/api.txt",
    "/apikey.txt",
    "/api_key.txt",
    "/token.txt",
    "/tokens.txt",
    "/auth.txt",
    "/login.txt",
    "/admin.txt",
    "/backup.txt",
    "/notes.txt",
    "/todo.txt",
    "/private.txt",
    "/confidential.txt",
    "/sensitive.txt",
    "/internal.txt",
    "/dev.txt",
    "/development.txt",
    "/prod.txt",
    "/production.txt",
    "/staging.txt",
    "/test.txt",
    "/testing.txt",
    "/debug.txt",
    "/log.txt",
    "/logs.txt",
    "/error.txt",
    "/errors.txt",
    "/access.txt",
    "/security.txt",
    "/users.txt",
    "/user.txt",
    "/accounts.txt",
    "/account.txt",
    "/db_config.txt",
    "/database_config.txt",
    "/app_config.txt",
    "/server.txt",
    "/servers.txt",
    "/host.txt",
    "/hosts.txt",
    "/connection.txt",
    "/connections.txt",
    "/connect.txt",
    "/mysql.txt",
    "/postgres.txt",
    "/mongodb.txt",
    "/redis.txt",
    "/firebase.txt",
    "/aws.txt",
    "/azure.txt",
    "/gcp.txt",
    "/google.txt",
    "/github.txt",
    "/gitlab.txt",
    "/bitbucket.txt",
    "/ftp.txt",
    "/ssh.txt",
    "/ssl.txt",
    "/cert.txt",
    "/certificate.txt",
    "/smtp.txt",
    "/email.txt",
    "/mail.txt",
    "/webhook.txt",
    "/webhooks.txt",
    "/endpoint.txt",
    "/endpoints.txt",
    "/url.txt",
    "/urls.txt",
    "/link.txt",
    "/links.txt",
    
    # ver control
    "/.git",
    "/.git/config",
    "/.git/HEAD",
    "/.git/logs/HEAD",
    "/.git/refs/heads/master",
    "/.git/refs/heads/main",
    "/.gitignore",
    "/.gitattributes",
    "/.svn",
    "/.svn/entries",
    "/.hg",
    "/.hgignore",
    "/.bzr",
    
    # db files
    "/database.sqlite",
    "/database.db",
    "/db.sqlite3",
    "/data.db",
    "/database.sql",
    "/backup.sql",
    "/dump.sql",
    "/mysqldump.sql",
    "/database_backup.sql",
    "/db_backup.sql",
    
    # python
    "/__pycache__",
    "/.python-version",
    "/requirements.txt",
    "/Pipfile",
    "/Pipfile.lock",
    "/poetry.lock",
    "/pyproject.toml",
    "/setup.py",
    "/manage.py",
    "/settings.py",
    "/local_settings.py",
    "/production_settings.py",
    "/development_settings.py",
    "/django_settings.py",
    "/server.py",
    "main.py",
    "/app.py",
    "/run.py",
    "/wsgi.py",
    "/asgi.py",
    "/celeryconfig.py",
    "/.env.django",
    "/venv",
    "/env",
    "/.venv",
    
    # node, js, ts, react
    "/package.json",
    "/package-lock.json",
    "/yarn.lock",
    "/npm-debug.log",
    "/yarn-error.log",
    "/node_modules",
    "/.next",
    "/.nuxt", 
    "/dist",
    "/build",
    "/out",
    "/.env.local",
    "/.env.development.local",
    "/.env.production.local",
    "/next.config.js",
    "/nuxt.config.js",
    "/webpack.config.js",
    "/rollup.config.js",
    "/vite.config.js",
    "/tsconfig.json",
    "/jsconfig.json",
    "/.babelrc",
    "/.eslintrc",
    "/.eslintrc.js",
    "/.eslintrc.json",
    "/prettier.config.js",
    "/.prettierrc",
    "/jest.config.js",
    "/cypress.json",
    "/.nvmrc",
    
    # php
    "/composer.json",
    "/composer.lock",
    "/vendor",
    "/.htaccess",
    "/php.ini",
    "/.user.ini",
    "/wp-config.php",
    "/wp-config-sample.php",
    "/wp-content/debug.log",
    "/wp-admin",
    "/phpmyadmin",
    "/phpinfo.php",
    "/info.php",
    "/test.php",
    "/config.inc.php",
    "/configuration.php",
    "/globals.php",
    "/connect.php",
    "/connection.php",
    "/database.php",
    "/db_connect.php",
    "/.env.php",
    
    # ruby
    "/Gemfile",
    "/Gemfile.lock",
    "/.bundle",
    "/.rbenv-version",
    "/.ruby-version",
    "/.rvmrc",
    "/config.ru",
    "/Rakefile",
    "/config/database.yml",
    "/config/secrets.yml",
    "/config/application.rb",
    "/config/environment.rb",
    "/config/routes.rb",
    
    # go
    "/go.mod",
    "/go.sum",
    "/main.go",
    "/Makefile",
    "/.air.toml",
    
    # replit
    "/.replit",
    "/replit.nix",
    "/.upm",
    
    # cloud/devops stuff
    "/Dockerfile",
    "/docker-compose.yml",
    "/docker-compose.yaml",
    "/.dockerignore",
    "/terraform.tfstate",
    "/terraform.tfvars",
    "/.terraform",
    "/ansible.cfg",
    "/inventory.yml",
    "/playbook.yml",
    "/.github",
    "/.gitlab-ci.yml",
    "/.travis.yml",
    "/appveyor.yml",
    "/circle.yml",
    "/Jenkinsfile",
    "/.drone.yml",
    "/kubernetes.yml",
    "/k8s.yml",
    "/deployment.yml",
    
    # aws
    "/.aws",
    "/.aws/credentials",
    "/.aws/config",
    "/aws.json",
    
    # azure
    "/.azure",
    "/azure.json",
    
    # gcp
    "/service-account.json",
    "/gcp-key.json",
    "/.gcloud",
    
    # editors
    "/.vscode",
    "/.idea",
    "/.vs",
    "/nbproject",
    "/.sublime-project",
    "/.sublime-workspace",
    "/Desktop.ini",
    "/Thumbs.db",
    "/.DS_Store",
    
    # logs
    "/error.log",
    "/access.log",
    "/error_log",
    "/access_log",
    "/application.log",
    "/debug.log",
    "/laravel.log",
    "/storage/logs",
    "/logs",
    "/log",
    "/var/log",
    
    # backups
    "/backup",
    "/backups",
    "/backup.zip",
    "/backup.tar.gz",
    "/site_backup.zip",
    "/database_backup.zip",
    "/backup.sql",
    "/dump.tar.gz",
    "/.backup",
    
    # admin stuff
    "/admin",
    "/administrator",
    "/wp-admin",
    "/cpanel",
    "/phpmyadmin",
    "/pma",
    "/adminer",
    "/webmail",
    "/mail",
    "/ftp",
    "/ssh",
    "/sftp",
    "/shell",
    "/console",
    "/terminal",
    "/cmd",
    "/debug",
    "/test",
    "/dev",
    "/development",
    "/staging",
    "/internal",
    "/private",
    "/secret",
    "/hidden",
    "/temp",
    "/tmp",
    "/cache",
    
    # api and debug
    "/api/debug",
    "/api/test",
    "/api/internal",
    "/debug",
    "/debug.php",
    "/phpinfo",
    "/server-status",
    "/server-info",
    "/_debug",
    "/_internal",
    "/_test",
    "/health",
    "/status",
    "/metrics",
    "/prometheus",
    "/actuator",
    "/actuator/health",
    "/actuator/env",
    
    # sec files
    "/robots.txt",
    "/sitemap.xml",
    "/crossdomain.xml",
    "/clientaccesspolicy.xml",
    "/.well-known",
    "/.well-known/security.txt",
    "/security.txt",
    
    # commons
    "/readme.txt",
    "/README.md",
    "/CHANGELOG.md",
    "/LICENSE",
    "/TODO.txt",
    "/INSTALL.txt",
    "/UPGRADE.txt",
    
    # framework
    # Laravel
    "/storage/framework/sessions",
    "/storage/framework/cache",
    "/bootstrap/cache",
    "/.env.example",
    "/artisan",
    
    # Django
    "/static",
    "/staticfiles",
    "/media",
    
    # Flask
    "/instance",
    "/static",
    
    # Express.js
    "/public",
    "/static",
    
    # Spring Boot
    "/application.properties",
    "/application.yml",
    "/bootstrap.properties",
    
    # ASP.NET
    "/bin",
    "/App_Data",
    "/App_Code",
    
    # test
    "/test.html",
    "/test.php",
    "/test.asp",
    "/test.jsp",
    "/phptest.php",
    "/testing",
    "/tests",
    "/__tests__",
    "/spec",
    "/cypress",
    
    # cms
    # WordPress
    "/wp-content/uploads",
    "/wp-includes",
    "/wp-admin/admin-ajax.php",
    
    # Drupal
    "/sites/default/files",
    "/sites/default/settings.php",
    
    # Joomla
    "/configuration.php",
    "/administrator",
    
    # paths
    "/assets", 
    "/static",
    "/public",
    "/files",
    "/uploads",
    "/images",
    "/css",
    "/js",
    "/media",
    "/docs",
    "/documentation"
)

Write-Host "Scanning $site for accessible sensitive files..." -ForegroundColor Cyan
Write-Host ""

$accessibleCount = 0
$totalScanned = 0

foreach ($target in $sensitiveTargets) {
    $totalScanned++
    try {
        $response = Invoke-WebRequest -Uri "$site$target" -Method GET -TimeoutSec 10 -ErrorAction Stop -UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        
        $accessibleCount++
        Write-Host "✅ $site$target" -ForegroundColor Green
        
    }
    catch {
        $statusCode = if ($_.Exception.Response) { $_.Exception.Response.StatusCode.Value__ } else { "Unknown" }
        Write-Host "$target" -ForegroundColor DarkGray
    }
}